/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sleeve-only.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sleeve-only.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['10013_-_WOMENS_SLEEVES'].geometry} material={materials['Dress_1:Left_Side_Sleeve']} rotation={[0, 0, Math.PI / 9]} scale={0.394} />
      <mesh geometry={nodes['10013_-_WOMENS_SLEEVES_1'].geometry} material={materials['Dress_1:Right_Side_Sleeve']} rotation={[0, 0, -Math.PI / 9]} scale={0.394} />
    </group>
  )
}

useGLTF.preload('/sleeve-only.glb')
