/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 short-sleeve-hitting-tee.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/short-sleeve-hitting-tee.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.394}>
        <mesh geometry={nodes['31104_-_WOMEN_SHORT_SLEEVE_WARMUP_1'].geometry} material={materials.blinn4} />
        <mesh geometry={nodes['31104_-_WOMEN_SHORT_SLEEVE_WARMUP_2'].geometry} material={materials.blinn3} />
        <mesh geometry={nodes['31104_-_WOMEN_SHORT_SLEEVE_WARMUP_3'].geometry} material={materials.blinn1} />
        <mesh geometry={nodes['31104_-_WOMEN_SHORT_SLEEVE_WARMUP_4'].geometry} material={materials.blinn2} />
        <mesh geometry={nodes['31104_-_WOMEN_SHORT_SLEEVE_WARMUP_5'].geometry} material={materials.Dress_1_Group6255_0001} />
        <mesh geometry={nodes['31104_-_WOMEN_SHORT_SLEEVE_WARMUP_6'].geometry} material={materials.blinn5} />
      </group>
    </group>
  )
}

useGLTF.preload('/short-sleeve-hitting-tee.glb')
