/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sleeveless-jersey.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sleeveless-jersey.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.394}>
        <mesh geometry={nodes.Dress_1_Group6255_1.geometry} material={materials.Back_Bodice} />
        <mesh geometry={nodes.Dress_1_Group6255_2.geometry} material={materials.Front_Bodice} />
        <mesh geometry={nodes.Dress_1_Group6255_3.geometry} material={materials.Front_Neck} />
        <mesh geometry={nodes.Dress_1_Group6255_4.geometry} material={materials.Back_Neck} />
      </group>
    </group>
  )
}

useGLTF.preload('/sleeveless-jersey.glb')
