name: Ren-Ath-Uniform Develop-Frontend Code 
on:
  push:
    branches:
      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        env:
          ENV_VARIABLE: ${{ secrets.DEV_ENV_VARIABLE }}
        run: |
          echo "${ENV_VARIABLE}" >> .env

      - name: Generating Unique tag
        id: generate-id
        run: echo "::set-output name=unique_id::$(date +'%Y-%m-%d-%H-%M-%S')"

      - name: Build Docker image
        run: docker build -t 438786549001.dkr.ecr.us-east-1.amazonaws.com/ren-ath:uniform-frotend-dev .

      - name: Login to AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ID }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Login to Elastic Container Registry
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 438786549001.dkr.ecr.us-east-1.amazonaws.com

      - name: Tagging image
        run: docker tag 438786549001.dkr.ecr.us-east-1.amazonaws.com/ren-ath:uniform-frontend-dev 438786549001.dkr.ecr.us-east-1.amazonaws.com/ren-ath:uniform-frontend-dev-${{ steps.generate-id.outputs.unique_id }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push 438786549001.dkr.ecr.us-east-1.amazonaws.com/ren-ath:uniform-frontend-dev
          docker push 438786549001.dkr.ecr.us-east-1.amazonaws.com/ren-ath:uniform-frontend-dev-${{ steps.generate-id.outputs.unique_id }}

  Deploy:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
        - name: SSH to Instance
          env:
            HOSTNAME: ${{ secrets.DEV_SSH_HOST }}
            USER_NAME: ${{ secrets.DEV_USER_NAME }}
          run: |
            echo "${{ secrets.DEV_SSH_PRIVATEKEY }}" > my-ssh-key.pem
            chmod 400 my-ssh-key.pem
            ssh -o StrictHostKeyChecking=no -i my-ssh-key.pem $USER_NAME@${HOSTNAME} '
            set -e
            echo "Setting aws login variable"
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ID }}
            aws configure set region ${{ secrets.AWS_REGION }}
            aws configure set output table
            echo "Done"
            echo "Docker Login"
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 438786549001.dkr.ecr.us-east-1.amazonaws.com
            echo "pulling image"
            docker pull 438786549001.dkr.ecr.us-east-1.amazonaws.com/ren-ath:uniform-frontend-dev
            echo "Done"
            echo "deleting existing container if any."
            frontend
            UNIQUE_ID=$(date +%s)
            CONTAINER_NAME="ren-ath-uniform-frontend-dev-${UNIQUE_ID}"
            echo "Starting Docker container..."
            sudo docker run -d --name $CONTAINER_NAME --restart always -p 81:81 438786549001.dkr.ecr.us-east-1.amazonaws.com/ren-ath:uniform-frontend-dev
            echo "Docker container started......."
            docker system prune -a --force
            '
