/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 long-sleeve-hitting-tees-with-hood.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/long-sleeve-hitting-tees-with-hood.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.394}>
        <mesh geometry={nodes['31106-women-long-sleeve-sub-warmup-w-hood_1'].geometry} material={materials.blinn2} />
        <mesh geometry={nodes['31106-women-long-sleeve-sub-warmup-w-hood_2'].geometry} material={materials.Dress_1_Group6255_0003_Dress_1_Group6255_0003_blinn} />
        <mesh geometry={nodes['31106-women-long-sleeve-sub-warmup-w-hood_3'].geometry} material={materials.blinn4} />
        <mesh geometry={nodes['31106-women-long-sleeve-sub-warmup-w-hood_4'].geometry} material={materials.blinn3} />
        <mesh geometry={nodes['31106-women-long-sleeve-sub-warmup-w-hood_5'].geometry} material={materials.blinn1} />
      </group>
    </group>
  )
}

useGLTF.preload('/long-sleeve-hitting-tees-with-hood.glb')
